name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
    
    - name: Install dependencies
      run: bun install
    
    - name: Compile TypeScript
      run: bunx tsc -p ./
    
    - name: Run ultracite lint check
      run: bunx ultracite lint
    
    - name: Run markdownlint-cli2
      run: bunx markdownlint-cli2 "**/*.md" "#node_modules"
    
    - name: Install vsce
      run: npm install -g vsce
    
    - name: Package extension
      run: vsce package
    
    - name: Upload VSIX
      uses: actions/upload-artifact@v4
      with:
        name: extension-package
        path: '*.vsix'